### ISSUE TITLE
Create Go api to receive Flux Alert to view payload

### ISSUE THREAD

**Issue by bradmccoydev** [keptn-sandbox/keptn-flux-integration#2]
Because the Flux generic webhook provider (notification.toolkit.fluxcd.io/v1beta1 - Provider) has a hardcoded payload, we need to create a small app that will get this payload and transfer it into a cloud event and send it to Keptn to trigger a sequence.

Payload example:

`{
  "involvedObject": {
    "kind":"GitRepository",
    "namespace":"flux-system",
    "name":"flux-system",
    "uid":"cc4d0095-83f4-4f08-98f2-d2e9f3731fb9",
    "apiVersion":"source.toolkit.fluxcd.io/v1beta2",
    "resourceVersion":"56921",
  },
  "severity":"info",
  "timestamp":"2006-01-02T15:04:05Z",
  "message":"Fetched revision: main/731f7eaddfb6af01cb2173e18f0f75b0ba780ef1",
  "reason":"info",
  "reportingController":"source-controller",
  "reportingInstance":"source-controller-7c7b47f5f-8bhrp",
}`

Flux Provider example:

`apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: keptn
  namespace: flux-system
spec:
  type: generic
  address: https://flux.bradmccoy.io
  secretRef:
    name: keptn-secret`

Flux Secret Example:

`apiVersion: v1
kind: Secret
metadata:
  name: keptn-secret
  namespace: flux-system
stringData:
  headers: |
     Authorization: token
     X-Forwarded-Proto: https`

note we can add whatever headers we want and add the address url also

**Comment by bradmccoydev** [comment]
Pull Request raised: https://github.com/keptn-sandbox/keptn-flux-integration/pull/3

**Comment by mehabhalodiya** [comment]
This issue is addressed in the linked PR, so closing this!
